# Generated by Django 4.0.1 on 2022-01-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=10)),
                ('grade', models.IntegerField()),
                ('department', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('is_present', models.BooleanField(default=False)),
                ('bio', models.TextField()),
            ],
        ),
    ]
