# Generated by Django 4.0.1 on 2022-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_student_dob_alter_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10, null=True),
        ),
    ]
