# Generated by Django 4.0.1 on 2022-01-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_student_website_alter_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirlStudent',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.student')),
                ('last_mensuration_date', models.DateField()),
            ],
            bases=('course.student',),
        ),
    ]
